### ISSUE TITLE
Allow for disabling of Components

### ISSUE THREAD

**Issue by KnechtionsCoding** [bentoml/Yatai#236]
In the Admin Guide it states:
```
* **Yatai-components:**

    Yatai groups dependency services into components for easy management. These dependency services are deployed in the `yatai-components` namespace. Yatai installs the default deployment component after the service start.

    *Components and their managed services:*

    * *Deployment*: Nginx Ingress Controller, Minio, Docker Registry

    * *Logging*: Loki, Grafana

    * *Monitoring*: Prometheus, Grafana
```

This should not be done by yatai/the operator, and instead be done by the helm chart that installs the operator.

Having it in the operator prevents a lot of control on the part of the user who may want to use their own grafana, prometheus, alternative logging systems, ingresses, etc.

Either provide a way to disable the creation of these components, or the better option, move them to the helm chart.

**Comment by parano** [comment]
Hi @KnechtionsCoding - thank you for the feedback! The reason for installing these components by Yatai instead of the Helm chat, is for Yatai to support multiple clusters. This way, users can bringing in additional k8s cluster to be managed by one Yatai instance.  It's indeed a problem that it becomes less customizable this way, I think a better approach is to have a separate `Yatai-cluster-components` helm chat, which is required to be installed before adding a cluster to Yatai.

Note that currently only the deployment component is installed by default. The logging and monitoring component are disabled by default, and can be installed from the Cluster UI page by the user. Does this work for your current setting?

**Comment by KnechtionsCoding** [comment]
No, because the namespaces are still created by the yatai operator, even if the parts deployed are disabled.

Means that if you have requirements around labels/settings the NS must have it's not clear who owns it.

**Comment by KnechtionsCoding** [comment]
I'd definitely prefer the separate chart approach because it would afford a lot more flexibility and control.

**Comment by yubozhao** [comment]
@KnechtionsCoding 

Hey, as discussed on slack, We made PRs (https://github.com/bentoml/yatai-chart/pull/40 and https://github.com/bentoml/Yatai/pull/237) to address this issue. 

Feel free to have more reopen it.
