### ISSUE TITLE
Support tolerations for internal components

### ISSUE THREAD

**Issue by mts-dyt** [bentoml/Yatai#277]
Hi bento team,

Toleration is supported only for `yatai-server`
Internal components doesn't support tolerations so we can't have a dedicated nodepool for yatai.
Is it possible to include this property for all deployment done by Yatai?

Thanks.

**Comment by yetone** [comment]
Thank you for your suggestion, we will consider adding this feature in the future

**Comment by benjamintanweihao** [comment]
I have a similar use case. I'm having troubles with `bento push` where the second step which builds the Bento Docker image fails. I suspect that this might be due to using the Google Container optimized image. I have therefore created another node pool that uses the Ubuntu image. 

I've also noticed that setting the tolerations in the Helm chart only affects `yatai-system`. Is there a workaround to set it on `yatai-builders`?

**Comment by yetone** [comment]
Now that yatai is no longer integrated with other infrastructure, this requirement no longer exists
