### ISSUE TITLE
Question: Do you have any plans to abstract database layers? (support mysql not only postgresql)

### ISSUE THREAD

**Issue by KimSoungRyoul** [bentoml/Yatai#363]
I think that yatai's api-server query is not complexity.  

I need these feature. 

if your team has a plan to support mysql not only postgresql and priority is not high, I'll make pullrequest

**Comment by yetone** [comment]
Recently there is no such plan, because the expression ability of Go is too low, so its ORM does not have a higher level of abstraction layer, you need to write SQL manually, and can not completely shield the differences of each SQL dialect, which means that you need to support new SQL dialects to rewrite every sentence of SQL in the project with the new dialect, leaving aside the complex testing work this is still a very horrible workload, so for the time being do not consider supporting other SQL dialects

**Comment by KimSoungRyoul** [comment]
thank you for your detailed answer 

I close this issue
